import type { LiquidityPool } from "./types";

export const pools: LiquidityPool[] = [
  {
    id: "op-velo-op-usdc",
    network: "OP Mainnet",
    dex: "Velodrome",
    pair: "OP / USDC",
    priority: true,
    tvlUsd: 18400000,
    tvlChange7dPct: 7.8,
    volume30dUsd: 134000000,
    fees30dUsd: 402000,
    feeAprPct: 26.2,
    utilizationPct: 72,
    liquidityDepthUsd: 9800000,
    health: "Strong",
    outcomeTarget: "Monitor incentives",
    note: "Core Optimism governance-token liquidity with healthy depth and fee output.",
  },
  {
    id: "base-aero-weth-usdc",
    network: "Base",
    dex: "Aerodrome",
    pair: "WETH / USDC",
    priority: true,
    tvlUsd: 39200000,
    tvlChange7dPct: 3.1,
    volume30dUsd: 265000000,
    fees30dUsd: 795000,
    feeAprPct: 24.3,
    utilizationPct: 69,
    liquidityDepthUsd: 22300000,
    health: "Strong",
    outcomeTarget: "Monitor incentives",
    note: "Largest tracked Base pool in the sample set; useful benchmark for fee efficiency.",
  },
  {
    id: "uni-uni-usdc",
    network: "Unichain",
    dex: "Uniswap v3",
    pair: "UNI / USDC",
    priority: true,
    tvlUsd: 9600000,
    tvlChange7dPct: 18.4,
    volume30dUsd: 78000000,
    fees30dUsd: 234000,
    feeAprPct: 29.2,
    utilizationPct: 77,
    liquidityDepthUsd: 5100000,
    health: "Strong",
    outcomeTarget: "Grow TVL",
    note: "High growth with strong utilization; needs deeper liquidity to reduce slippage.",
  },
  {
    id: "op-uni-op-weth",
    network: "OP Mainnet",
    dex: "Uniswap v3",
    pair: "OP / WETH",
    priority: true,
    tvlUsd: 7100000,
    tvlChange7dPct: -4.6,
    volume30dUsd: 28000000,
    fees30dUsd: 84000,
    feeAprPct: 14.2,
    utilizationPct: 48,
    liquidityDepthUsd: 3600000,
    health: "Watch",
    outcomeTarget: "Improve fee efficiency",
    note: "Fees lag relative to TVL. Needs volume analysis before additional OP incentives.",
  },
  {
    id: "base-aero-usdc-usdt",
    network: "Base",
    dex: "Aerodrome",
    pair: "USDC / USDT",
    priority: true,
    tvlUsd: 24500000,
    tvlChange7dPct: -2.3,
    volume30dUsd: 112000000,
    fees30dUsd: 112000,
    feeAprPct: 5.5,
    utilizationPct: 38,
    liquidityDepthUsd: 20100000,
    health: "Watch",
    outcomeTarget: "Rebalance liquidity",
    note: "Deep liquidity, weaker fee output. Useful for stable routing but not fee growth.",
  },
  {
    id: "mode-kim-mode-weth",
    network: "Mode",
    dex: "Kim Exchange",
    pair: "MODE / WETH",
    priority: true,
    tvlUsd: 2800000,
    tvlChange7dPct: 22.7,
    volume30dUsd: 11600000,
    fees30dUsd: 34800,
    feeAprPct: 14.9,
    utilizationPct: 55,
    liquidityDepthUsd: 1450000,
    health: "Watch",
    outcomeTarget: "Grow TVL",
    note: "Emerging Superchain network pool with growth but shallow depth.",
  },
  {
    id: "zora-uni-zora-weth",
    network: "Zora",
    dex: "Uniswap v3",
    pair: "ZORA / WETH",
    priority: false,
    tvlUsd: 940000,
    tvlChange7dPct: -12.1,
    volume30dUsd: 2400000,
    fees30dUsd: 7200,
    feeAprPct: 9.2,
    utilizationPct: 35,
    liquidityDepthUsd: 410000,
    health: "At risk",
    outcomeTarget: "Rebalance liquidity",
    note: "Low depth and declining TVL. Needs monitoring before incentive allocation.",
  },
  {
    id: "base-uni-cb-eth",
    network: "Base",
    dex: "Uniswap v3",
    pair: "cbBTC / ETH",
    priority: true,
    tvlUsd: 11600000,
    tvlChange7dPct: 9.5,
    volume30dUsd: 36500000,
    fees30dUsd: 146000,
    feeAprPct: 15.1,
    utilizationPct: 51,
    liquidityDepthUsd: 6900000,
    health: "Strong",
    outcomeTarget: "Improve fee efficiency",
    note: "Healthy growth, but volume concentration should be tracked across venues.",
  },
];
